### PR TITLE
Merchandise rework

### LINKED ISSUE #60: Rework merchandise orders
Currently, when a guest (not logged in user) goes to the merchandise page, an errors pops up that says "Failed to load orders". Maybe it would be best to either omit that error if user isn't logged in and require login for ordering merchandise?

Also consider

- implementing shopping cart
- move order history to shopping cart page

### PR DESCRIPTION
**Pull request by Xomin1**
## Summary

Implemented improvements for the merchandise page.

## Changes made

- Prevented the “Failed to load orders” error from showing when the user is not logged in.
- Ordering merchandise is restricted to logged-in users.
- Added logic to check authentication before attempting to load user orders.
- Separated order history from the main merchandise page.
- Added ,,Your orders" page"
- Moved orders history to ,,Your orders" page
- Added shopping cart-related functionality for merchandise ordering.

Closes #60

### CODE REVIEW

File: frontend/src/pages/Merchandise/CartPage.tsx [hunk 1]
```diff
@@ -0,0 +1,319 @@
+import { useEffect, useState } from 'react';
+import { useNavigate } from 'react-router-dom';
+import Navbar from '../../components/layout/Navbar';
+import * as merchandiseService from '../../services/merchandiseService';
+import type { Merchandise } from '../../types/Merchandise';
+import './MerchandisePage.css';
+
+type CartItem = {
```
Comment (Teshyo) [inline frontend/src/pages/Merchandise/CartPage.tsx]: is it possible to create a cartItem.ts type file in types folder and import that type here and in the merchPage.tsx? (instead of declaring this type twice for two folders)

**Review by Teshyo — CHANGES_REQUESTED** [review]

**Review by Teshyo — APPROVED** [review]
+rep
